# Site settings | 网站设置
title: 青泉博客
SEOTitle: hfming 博客 | 青泉博客
header-img: "https://hfm-blog.oss-cn-hangzhou.aliyuncs.com/github/hfming.github.io/coffee-java.jpg"
email: hfming2016@163.com
description: "hfming 博客"
keyword: "hfming, hfming 博客, 青泉博客, java blog, blog, java"
url: "http://hfming.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/hfming/hfming.github.io.git" #code repository | 代码仓库


# Sidebar settings | 侧边栏设置
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: ""
sidebar-avatar: "https://hfm-resume.oss-cn-hangzhou.aliyuncs.com/%E4%B8%AA%E4%BA%BA%E5%BE%AE%E4%BF%A1%E5%9B%BE%E6%A0%87.png"

# SNS settings | 社交网络设置
facebook_username:
github_username: hfming
zhihu_username: hfming2016
csdn_username: hfming2016
gitee_username: hfming2016
wordpress_username: hfming

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
# 转换时排除某些文件夹或文件。被排除的文件或文件夹的路径是相对于网站源码目录的，源码目录以外不受影响。
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
Regeneration: true    # 允许文件修改时自动重新生成网站。

# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
input: GFM                            # use Github Flavored Markdown !important

# Gitalk
gitalk:
        enable: true    # 是否开启Gitalk评论
        clientID: f098e835226554c7732c                          #生成的clientID
        clientSecret: 1daf8a0bdbe1d830d5816db9c9345ffdfc27dde2   #生成的clientSecret
        repo: hfming.github.io    #仓库名称
        owner: hfming    # github用户名
        admin: hfming
        distractionFreeMode: true # 是否启用类似FB的阴影遮罩

# 统计
# Analytics settings
# Baidu Analytics
ba_track_id: fd0ddd4dd9b56f7f3591bd3b26f32147

# Google Analytics
ga_track_id:            # Format: UA-xxxxxx-xx
ga_domain:               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto

# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Friends
链接: [
    {
        title: "GitHub.hfming",
        href: "http://hfming.github.io"
    },{
        title: "CSDN·hfming2016",
        href: "https://blog.csdn.net/hfming2016"
    },{
        title: "知乎·hfming2016",
        href: "https://www.zhihu.com/people/hfming2016"
    },{
        title: "Gitee·hfming2016",
        href: "https://gitee.com/hfming2016"
    },{
        title: "WordPress·hfming",
        href: "https://www.hfming.com"
    }
]
